// Verifies that the per-juz shards generated by `tool/shard_editions.dart`
// reconstruct their source monolith EXACTLY, using the same page->juz
// resolution the web repository uses at runtime.
//
// This is the correctness proof for the sharding change: the reader assembles a
// page by fetching the shard(s) whose page range covers it and concatenating,
// so if the split or the index boundaries were wrong the app would silently
// show a page with missing or duplicated ayahs. Cheap to run, and it fails loud
// if anyone regenerates the data incorrectly or hand-edits a shard.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const String _editionsDir = 'data/editions';

/// Fully cross-checked against its monolith (all 604 pages).
const String _fullCheckEdition = 'quran-simple';

/// A tafsir, checked for completeness only — same code path, different data
/// shape (long texts, and it is one of the editions that could not be served
/// whole because of jsDelivr's 20 MB limit).
const String _spotCheckEdition = 'ar.jalalayn';

const int _totalAyahs = 6236;
const int _totalPages = 604;
const int _juzCount = 30;

Map<String, dynamic> _readJson(String path) =>
    json.decode(File(path).readAsStringSync()) as Map<String, dynamic>;

/// Mirrors `_EditionIndex.juzForPage` in `quran_repository_web.dart`: every juz
/// whose page range covers [page]. Ranges deliberately overlap on the four
/// straddle pages.
List<int> _juzForPage(List<Map<String, dynamic>> juz, int page) => juz
    .where((j) =>
        page >= (j['firstPage'] as num).toInt() &&
        page <= (j['lastPage'] as num).toInt())
    .map((j) => (j['n'] as num).toInt())
    .toList()
  ..sort();

/// Flattens an edition monolith to page -> ordered ayah numbers.
Map<int, List<int>> _monolithPages(Map<String, dynamic> decoded) {
  final out = <int, List<int>>{};
  final surahs = (decoded['data']['surahs'] as List<dynamic>);
  for (final s in surahs) {
    for (final a in (s as Map<String, dynamic>)['ayahs'] as List<dynamic>) {
      final m = a as Map<String, dynamic>;
      (out[(m['page'] as num).toInt()] ??= <int>[])
          .add((m['number'] as num).toInt());
    }
  }
  return out;
}

/// Loads all 30 shards of [edition] and returns them keyed by juz number.
Map<int, Map<String, dynamic>> _loadShards(String edition) {
  final shards = <int, Map<String, dynamic>>{};
  for (var juz = 1; juz <= _juzCount; juz++) {
    final padded = juz.toString().padLeft(2, '0');
    shards[juz] = _readJson('$_editionsDir/$edition/juz-$padded.json');
  }
  return shards;
}

/// page -> ordered ayah numbers, as the runtime would assemble it: shards in
/// ascending juz order, concatenating each shard's ayahs for that page.
Map<int, List<int>> _shardedPages(
  Map<int, Map<String, dynamic>> shards,
  List<Map<String, dynamic>> juzIndex,
) {
  // Index each shard by page first, exactly like `_Shard.fromJson`.
  final byJuzThenPage = <int, Map<int, List<int>>>{};
  for (final entry in shards.entries) {
    final byPage = <int, List<int>>{};
    for (final s in (entry.value['surahs'] as List<dynamic>)) {
      for (final a in (s as Map<String, dynamic>)['ayahs'] as List<dynamic>) {
        final m = a as Map<String, dynamic>;
        (byPage[(m['page'] as num).toInt()] ??= <int>[])
            .add((m['number'] as num).toInt());
      }
    }
    byJuzThenPage[entry.key] = byPage;
  }

  final out = <int, List<int>>{};
  for (var page = 1; page <= _totalPages; page++) {
    final ayahs = <int>[];
    for (final juz in _juzForPage(juzIndex, page)) {
      final onPage = byJuzThenPage[juz]?[page];
      if (onPage != null) ayahs.addAll(onPage);
    }
    if (ayahs.isNotEmpty) out[page] = ayahs;
  }
  return out;
}

void main() {
  final indexJson = _readJson('$_editionsDir/index.json');
  final juzIndex = (indexJson['juz'] as List<dynamic>)
      .cast<Map<String, dynamic>>();

  group('index.json', () {
    test('declares the expected totals', () {
      expect(indexJson['juzCount'], _juzCount);
      expect(indexJson['totalAyahs'], _totalAyahs);
      expect(indexJson['totalPages'], _totalPages);
      expect((indexJson['surahs'] as List).length, 114);
    });

    test('juz ayah ranges are contiguous and cover 1..6236 without overlap',
        () {
      final sorted = [...juzIndex]..sort(
          (a, b) => (a['n'] as num).compareTo(b['n'] as num));
      expect((sorted.first['startAyah'] as num).toInt(), 1);
      expect((sorted.last['endAyah'] as num).toInt(), _totalAyahs);
      for (var i = 1; i < sorted.length; i++) {
        final prevEnd = (sorted[i - 1]['endAyah'] as num).toInt();
        final thisStart = (sorted[i]['startAyah'] as num).toInt();
        expect(thisStart, prevEnd + 1,
            reason: 'gap/overlap between juz ${i} and ${i + 1}');
      }
    });

    test('every page resolves to at least one juz', () {
      for (var page = 1; page <= _totalPages; page++) {
        expect(_juzForPage(juzIndex, page), isNotEmpty,
            reason: 'page $page resolves to no juz');
      }
    });

    test('exactly four pages straddle a juz boundary', () {
      final straddling = <int>[];
      for (var page = 1; page <= _totalPages; page++) {
        if (_juzForPage(juzIndex, page).length > 1) straddling.add(page);
      }
      // Deliberately asserting the specific pages: if the mushaf page data ever
      // changes, the shard-fetching path needs re-checking, not silently
      // adapting.
      expect(straddling, <int>[62, 121, 201, 502]);
    });

    test('surah -> juz mapping is present and sane', () {
      final surahs = (indexJson['surahs'] as List<dynamic>)
          .cast<Map<String, dynamic>>();
      for (final s in surahs) {
        final juz = (s['juz'] as List<dynamic>).cast<num>();
        expect(juz, isNotEmpty, reason: 'surah ${s['number']} has no juz');
        expect((s['totalVerses'] as num).toInt(), greaterThan(0));
      }
      // Al-Baqarah spans juz 1-3.
      final baqarah = surahs.firstWhere((s) => s['number'] == 2);
      expect((baqarah['juz'] as List).cast<num>().map((n) => n.toInt()),
          <int>[1, 2, 3]);
      expect((baqarah['totalVerses'] as num).toInt(), 286);
    });
  });

  group('$_fullCheckEdition shards', () {
    late Map<int, Map<String, dynamic>> shards;
    late Map<int, List<int>> sharded;

    setUpAll(() {
      shards = _loadShards(_fullCheckEdition);
      sharded = _shardedPages(shards, juzIndex);
    });

    test('contain every ayah exactly once', () {
      final seen = <int>[];
      for (final shard in shards.values) {
        for (final s in (shard['surahs'] as List<dynamic>)) {
          for (final a in (s as Map<String, dynamic>)['ayahs'] as List<dynamic>) {
            seen.add(((a as Map<String, dynamic>)['number'] as num).toInt());
          }
        }
      }
      expect(seen.length, _totalAyahs);
      expect(seen.toSet().length, _totalAyahs, reason: 'duplicate ayah numbers');
    });

    test('every ayah lands in the juz the index claims', () {
      for (final entry in shards.entries) {
        final juzNumber = entry.key;
        for (final s in (entry.value['surahs'] as List<dynamic>)) {
          for (final a in (s as Map<String, dynamic>)['ayahs'] as List<dynamic>) {
            final m = a as Map<String, dynamic>;
            expect((m['juz'] as num).toInt(), juzNumber,
                reason: 'ayah ${m['number']} is in juz-$juzNumber but declares '
                    'juz ${m['juz']}');
          }
        }
      }
    });

    test('reassemble each of the 604 pages identically to the monolith', () {
      final monolith =
          _monolithPages(_readJson('$_editionsDir/$_fullCheckEdition.json'));

      expect(sharded.keys.toSet(), monolith.keys.toSet(),
          reason: 'page sets differ');

      for (var page = 1; page <= _totalPages; page++) {
        expect(sharded[page], monolith[page],
            reason: 'page $page differs (order matters)');
      }
    });

    test('straddle page 62 is assembled from two shards in ayah order', () {
      // Regression guard for the specific case the overlapping page ranges
      // exist to handle.
      expect(_juzForPage(juzIndex, 62), <int>[3, 4]);
      final page62 = sharded[62]!;
      expect(page62.first, 385);
      expect(page62, List<int>.generate(page62.length, (i) => 385 + i),
          reason: 'ayahs must be contiguous and ascending across the boundary');
    });
  });

  group('$_spotCheckEdition shards', () {
    test('contain every ayah exactly once', () {
      final shards = _loadShards(_spotCheckEdition);
      final seen = <int>{};
      for (final shard in shards.values) {
        for (final s in (shard['surahs'] as List<dynamic>)) {
          for (final a in (s as Map<String, dynamic>)['ayahs'] as List<dynamic>) {
            seen.add(((a as Map<String, dynamic>)['number'] as num).toInt());
          }
        }
      }
      expect(seen.length, _totalAyahs);
    });

    test('every shard stays under jsDelivr\'s 20 MB per-file limit', () {
      const limit = 20 * 1024 * 1024;
      for (var juz = 1; juz <= _juzCount; juz++) {
        final padded = juz.toString().padLeft(2, '0');
        for (final edition in Directory(_editionsDir)
            .listSync()
            .whereType<Directory>()) {
          final file = File('${edition.path}/juz-$padded.json');
          expect(file.existsSync(), isTrue,
              reason: '${edition.path}/juz-$padded.json is missing');
          expect(file.lengthSync(), lessThan(limit),
              reason: '${file.path} exceeds jsDelivr 20 MB limit');
        }
      }
    });
  });
}
